### ISSUE TITLE
is there a need to turn the webserver off and on again?

### ISSUE THREAD

**Issue by beleriandcrises** [whisperdancer/nextcloud-backup-restore#1]
Hi, 
I don't see a reason to turn the server off and on again, and it may give troubles if other services are running or people connect and have a server not found.

Just to doublecheck, I run the script with those part commented out and had no troubles. Am I missing something? If it's just your personal preference, maybe we can specify that in a comment?

Thanks for the script! =)

**Comment by whisperdancer** [comment]
Feel free to tweak the scripts to your liking. Just comment out the web server off and on lines. I prefer to keep it in my scripts. Glad you found the scripts useful. Cheers.
